trigger:
- develop

variables:
- group: SalesforceSecrets

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: Install Node.js

- script: |
    npm install --global @salesforce/cli
  displayName: Install Salesforce CLI

- script: |
    mkdir keys
    echo "$(JWT_SERVER_KEY)" > keys/server.key
  displayName: Create JWT Key File

- script: |
    sf org login jwt \
      --client-id "$(SF_CLIENT_ID)" \
      --jwt-key-file keys/server.key \
      --username "$(SF_USERNAME)" \
      --instance-url https://test.salesforce.com \
      --alias devSandbox
  displayName: Authenticate Dev Sandbox

- script: |
    sf org list
  displayName: Verify Org Login

- script: |
    sf project deploy start \
      --source-dir MySalesforceProject/force-app \
      --target-org devSandbox
  displayName: Deploy Metadata
