trigger:
  - main

variables:
  - group: ProdSecrets

pool:
  vmImage: ubuntu-latest

steps:
  # Checkout Repository
  - checkout: self

  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"
    displayName: Install Node.js

  # Install Salesforce CLI
  - script: |
      npm install --global sfdx-cli
    displayName: Install Salesforce CLI

  # Verify Salesforce CLI
  - script: |
      sfdx --version
    displayName: Verify Salesforce CLI

  # Authenticate PROD
  - script: |
      sfdx force:auth:jwt:grant \
        --clientid "$(SF_CLIENT_ID)" \
        --jwtkeyfile MySalesforceProject/keys/server.key \
        --username "$(SF_USERNAME)" \
        --instanceurl https://login.salesforce.com \
        --setdefaultusername \
        --setalias prodOrg
    displayName: Authenticate PROD

  # Verify Connected Org
  - script: |
      sfdx force:org:list
    displayName: Verify Org's Login

  # Deploy Salesforce Metadata
  - script: |
      cd MySalesforceProject
      sfdx force:source:deploy \
        -p force-app \
        -u prodOrg
    displayName: Deploy Metadata
