trigger:
- develop

variables:
- group: SalesforceSecrets

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: Install Node.js

# Install Salesforce CLI
- script: |
    npm install --global sfdx-cli
  displayName: Install Salesforce CLI

# Verify Salesforce CLI
- script: |
    sfdx --version
  displayName: Verify Salesforce CLI

# Create JWT Key File
- script: |
    mkdir keys
    echo "$(JWT_SERVER_KEY)" > keys/server.key
  displayName: Create JWT Key File

# Authenticate Salesforce Sandbox
- script: |
    sfdx force:auth:jwt:grant \
      --clientid "$(SF_CLIENT_ID)" \
      --jwtkeyfile keys/server.key \
      --username "$(SF_USERNAME)" \
      --instanceurl https://test.salesforce.com \
      --setdefaultusername \
      --setalias devSandbox
  displayName: Authenticate Dev Sandbox

# Verify Connected Org
- script: |
    sfdx force:org:list
  displayName: Verify Org Login

# Deploy Metadata
- script: |
    sfdx force:source:deploy \
      -p MySalesforceProject/force-app \
      -u devSandbox
  displayName: Deploy Metadata
